export const CONFIG = {

    STAGE_WIDTH: 1200,
    STAGE_HEIGHT: 800,

    PLAYER_LIFES_MAX: 10,
    PLAYER_BOOST_MAX: 100,
    SCORE_SINGLE_VALUE:  1,

    CONTROLS_HERO_SPEED: 3,

    BOOST_EXTRA_PER_SCORE: 10,
    BOOST_DROP_PER_FRAME: 0.5,

    ENEMIES_FREQUENCY: 0.5,
}